name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["Test"]
    branches: [main]
    types: 
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: yarn install

      - name: Build app
        run: yarn build
        env:
          REACT_APP_DOMAIN: ${{ vars.REACT_APP_DOMAIN }}
          REACT_APP_STYTCH_PROJECT_ENV: ${{ vars.REACT_APP_STYTCH_PROJECT_ENV }}
          REACT_APP_STYTCH_PUBLIC_TOKEN: ${{ vars.REACT_APP_STYTCH_PUBLIC_TOKEN }}
          REACT_APP_BACKEND_URL: ${{ vars.REACT_APP_BACKEND_URL }}
  
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
